### ISSUE TITLE
[vueapp] [small variants] Export of variant table doesn't work

### ISSUE THREAD

**Issue by xiamaz** [varfish-org/varfish-server#1115]
Currently the three options for exporting variant results (xlsx, tsv, vcf) do not work:

![image](https://github.com/bihealth/varfish-server/assets/3340720/2add1896-4e27-432c-b7b9-564486eb101f)

**Comment by stolpeo** [comment]
has been solved in the meantime. closing.

**Comment by flokraft85** [comment]
Are there any other changes include in the new version? After pull and compose up I got the "bad gateway" error.

**Comment by flokraft85** [comment]
Yes, of cause. 
--------------------------------------------------------
 docker-compose-wait 2.7.3
---------------------------
Starting with configuration:
 - Hosts to be waiting for: [postgres:5432, redis:6379]
 - Timeout before failure: 30 seconds 
 - TCP connection timeout before retry: 5 seconds 
 - Sleeping time before checking for hosts availability: 0 seconds
 - Sleeping time once all hosts are available: 0 seconds
 - Sleeping time between retries: 1 seconds
--------------------------------------------------------
Checking availability of postgres:5432
Host postgres:5432 is now available!
--------------------------------------------------------
Checking availability of  redis:6379
Host  redis:6379 is now available!
--------------------------------------------------------
docker-compose-wait - Everything's fine, the application can now start!
--------------------------------------------------------
VARFISH MIGRATIONS BEGIN
fatal: not a git repository (or any of the parent directories): .git
Operations to perform:
  Apply all migrations: admin, adminalerts, appalerts, auth, beaconsite, bgjobs, cases, cases_files, cases_import, cases_qc, clinvar, clinvar_export, cohorts, conservation, contenttypes, dbsnp, djangoplugins, extra_annos, frequencies, geneinfo, genepanels, genomicfeatures, hgmd, importer, knox, pathways, projectroles, regmaps, seqmeta, sessions, sites, svdbs, svs, timeline, users, var_stats_qc, varannos, variants
Running migrations:

**Comment by holtgrewe** [comment]
Ah, then it's still applying migrations and that may take some time.

**Comment by flokraft85** [comment]
OK, migration is done. However, still the same behavior. Clicking on one of the three download options does not work. There is for 1-2s the loading symbol and after that the cloud icon and the "Export to..." becoming red.

**Comment by holtgrewe** [comment]
OK, I'm reopening this and changing the size to "M" as it appears to be not so simple.

**Comment by stolpeo** [comment]
@flokraft85 That's interesting. I cannot reproduce it in my dev instance or our Berlin instance. Could you open the developer console in your browser and maybe screenshot any errors unless there is confidential information displayed?

**Comment by stolpeo** [comment]
RCA
====

Together with @flokraft85 we discovered that newly set up installation of VarFish do not start Jannovar. However, the molecular impact computation of the file export feature still relies on Jannovar. Jannovar can of course be disabled and the step will be skipped which should fix the problem, but if the intention was to replace the usage of Jannovar with annonars, this spot was probably missed. @holtgrewe What is your intention here? I can't find any other usage of Jannovar in the code base other than the file export.

Affected function:
https://github.com/varfish-org/varfish-server/blob/e6c6e831d7d83ab5961c960a32a74f525057be6f/variants/models/scores.py#L21

**Comment by holtgrewe** [comment]
@stolpeo that was an oversight. Please replace by mehari csq and remove all mention of Hannover if this is the last one.

Good catch!
